### ISSUE TITLE
无法获取App中配置的vuex存储信息

### ISSUE THREAD

**Issue by liangxuegang01** [CalvinVon/vue-mount#16]
**Describe the bug**
使用append模式加入到App节点下无法获取this.$store，已经配置了vuex

**To Reproduce**
Steps to reproduce the behavior.

**Version info**
0.6.2

**Error message**
this.$store为undefined

**Comment by CalvinVon** [comment]
先感谢你的使用和提出的 issue。

现在的确是个问题，不过你可以先暂时使用下面的临时方法替代。
```js
mount(HelloWorld, {
    target: this,
    mode: "append",
    data: {
        $store: this.$store
    }
});
```
新的修复版本会在近期发布。
[示例链接](https://codesandbox.io/s/magical-lamport-uw3vh?fontsize=14&hidenavigation=1&theme=dark) （查看console)

**Comment by CalvinVon** [comment]
更新：v0.6.3版本已修复，并且添加了中文文档的[解决方案](https://github.com/CalvinVon/vue-mount/blob/master/README_zh.md#无法访问到-routerstore) @liangxuegang01
