### ISSUE TITLE
What does API data mean?

### ISSUE THREAD

**Issue by wenxiayili** [CalvinVon/vue-mount#2]
what does 'modify component data ' mean? Could you explain? Thank you!

**Comment by CalvinVon** [comment]
Sorry to respond so late.
It means to modify the component's data after mounted.
Just like this:
```js
const AlertCmp = {
  data() {
    return {
      someInnerData: 'initialValue'
    }
  }
}

const vm = mount(AlertCmp);
vm.someInnerData = 'modified';
```

**Comment by wenxiayili** [comment]
> Sorry to respond so late.
> It means to modify the component's data after created(Correction: mounted is not necessary and I have updated in docs).
> Just like this:
> 
> ```js
> const AlertCmp = {
>   data() {
>     return {
>       someInnerData: 'initialValue'
>     }
>   }
> }
> 
> const vm = mount(AlertCmp);
> vm.someInnerData = 'modified';
> ```

谢谢您！不知道您会中文不？我在实际用的时候，遇到这个错误：
   Cannot read property 'subscribeDataChanging' of undefined
能否给我思路 让我排查下！

**Comment by CalvinVon** [comment]
> > Sorry to respond so late.
> > It means to modify the component's data after created(Correction: mounted is not necessary and I have updated in docs).
> > Just like this:
> > ```js
> > const AlertCmp = {
> >   data() {
> >     return {
> >       someInnerData: 'initialValue'
> >     }
> >   }
> > }
> > 
> > const vm = mount(AlertCmp);
> > vm.someInnerData = 'modified';
> > ```
> 
> 谢谢您！不知道您会中文不？我在实际用的时候，遇到这个错误：
> Cannot read property 'subscribeDataChanging' of undefined
> 能否给我思路 让我排查下！

麻烦贴一下代码

**Comment by wenxiayili** [comment]
> > > Sorry to respond so late.
> > > It means to modify the component's data after created(Correction: mounted is not necessary and I have updated in docs).
> > > Just like this:
> > > ```js
> > > const AlertCmp = {
> > >   data() {
> > >     return {
> > >       someInnerData: 'initialValue'
> > >     }
> > >   }
> > > }
> > > 
> > > const vm = mount(AlertCmp);
> > > vm.someInnerData = 'modified';
> > > ```
> > 
> > 
> > 谢谢您！不知道您会中文不？我在实际用的时候，遇到这个错误：
> > Cannot read property 'subscribeDataChanging' of undefined
> > 能否给我思路 让我排查下！
> 
> 麻烦贴一下代码
抱歉这么晚来，代码如下：
`mountCmp: function(type, id, setObj = null) {
      const cmp = getCmp(type)
      const props = getProps(type, setObj)
      let uid = '#m' + id
      const mtCmp = new Mount(cmp, {
        target: uid,
        mode: 'append',
        props: props
      })
      mtCmp.mount()
      mtCmps.push({
        ['m' + id]: mtCmp
      })
      console.log(mtCmps)
    } // 数据预览处理结束`
做下注释：cmp--就是要挂载的自定义组件，mtCmps是我管理所有mount实例的数组

**Comment by CalvinVon** [comment]
请确保：
- 版本为最新
- id 能够找到
- props数据获取正确

在以上情况下，这段代码没什么问题。
建议你排查一下是不是要挂载的组件问题。
控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。

**Comment by wenxiayili** [comment]
> 请确保：
> 
> * 版本为最新
> * id 能够找到
> * props数据获取正确
> 
> 在以上情况下，这段代码没什么问题。
> 建议你排查一下是不是要挂载的组件问题。
> 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。

组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然

**Comment by CalvinVon** [comment]
> > 请确保：
> > 
> > * 版本为最新
> > * id 能够找到
> > * props数据获取正确
> > 
> > 在以上情况下，这段代码没什么问题。
> > 建议你排查一下是不是要挂载的组件问题。
> > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> 
> 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然

`subscribeDataChanging`运行到这里的时候你可以打个断点看看。
我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
微信：GVsmart

**Comment by wenxiayili** [comment]
> > > 请确保：
> > > 
> > > * 版本为最新
> > > * id 能够找到
> > > * props数据获取正确
> > > 
> > > 在以上情况下，这段代码没什么问题。
> > > 建议你排查一下是不是要挂载的组件问题。
> > > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> > 
> > 
> > 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然
> 
> `subscribeDataChanging`运行到这里的时候你可以打个断点看看。
> 我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
> 微信：GVsmart

我等下根据您的建议，检查下我的代码，谢谢！

**Comment by CalvinVon** [comment]
> > > > 请确保：
> > > > 
> > > > * 版本为最新
> > > > * id 能够找到
> > > > * props数据获取正确
> > > > 
> > > > 在以上情况下，这段代码没什么问题。
> > > > 建议你排查一下是不是要挂载的组件问题。
> > > > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > > > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> > > 
> > > 
> > > 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然
> > 
> > 
> > `subscribeDataChanging`运行到这里的时候你可以打个断点看看。
> > 我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
> > 微信：GVsmart
> 
> 我等下根据您的建议，检查下我的代码，谢谢！

客气了

**Comment by wenxiayili** [comment]
> > > 请确保：
> > > 
> > > * 版本为最新
> > > * id 能够找到
> > > * props数据获取正确
> > > 
> > > 在以上情况下，这段代码没什么问题。
> > > 建议你排查一下是不是要挂载的组件问题。
> > > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> > 
> > 
> > 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然
> 
> `subscribeDataChanging`运行到这里的时候你可以打个断点看看。
> 我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
> 微信：GVsmart

前几天找到原因了，今天来把这个尾巴解决掉：是因为i18n国际化的问题，谢谢您！

**Comment by CalvinVon** [comment]
> > > > 请确保：
> > > > 
> > > > * 版本为最新
> > > > * id 能够找到
> > > > * props数据获取正确
> > > > 
> > > > 在以上情况下，这段代码没什么问题。
> > > > 建议你排查一下是不是要挂载的组件问题。
> > > > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > > > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> > > 
> > > 
> > > 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然
> > 
> > 
> > `subscribeDataChanging`运行到这里的时候你可以打个断点看看。
> > 我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
> > 微信：GVsmart
> 
> 前几天找到原因了，今天来把这个尾巴解决掉：是因为i18n国际化的问题，谢谢您！

不客气，国庆后上班快乐！: )

**Comment by cyanbaby** [comment]
> > > > > 请确保：
> > > > > 
> > > > > * 版本为最新
> > > > > * id 能够找到
> > > > > * props数据获取正确
> > > > > 
> > > > > 在以上情况下，这段代码没什么问题。
> > > > > 建议你排查一下是不是要挂载的组件问题。
> > > > > 控制台里的报错信息比较重要，你可以以此为介入点，打打断点。
> > > > > 另外，`subscribeDataChanging`这个错误像是你业务代码里的，建议你多排查一下。
> > > > 
> > > > 
> > > > 组件可以正常挂载且是正常的，但就是报这个错。。不知其所以然
> > > 
> > > 
> > > `subscribeDataChanging`运行到这里的时候你可以打个断点看看。
> > > 我确定不是我库里面的报错，你可以加我微信我可以帮你看看报错信息。
> > > 微信：GVsmart
> > 
> > 
> > 前几天找到原因了，今天来把这个尾巴解决掉：是因为i18n国际化的问题，谢谢您！
> 
> 不客气，国庆后上班快乐！: )

请问怎么解决的呢？
